// ── Initial state factory ─────────────────────────────────────────────────
// Called once per component instance. Dynamic defaults (now, batchJumpDate,
// Sets, isOnline) are evaluated freshly each time so instances never share
// mutable references.
const makeInitialState = () => ({
  // auth
  authed: false, role: null, authMode: 'login',
  currentUserId: null, me: null,
  authError: '', loading: false, accountDeleted: false,
  // form fields
  loginContact: '', loginPassword: '',
  suName: '', suContact: '', suShift: 'AM', suPassword: '',
  // live data
  personnel: [], attendance: {}, attendanceCache: {},
  batches: [], activeBatchIdx: 0,
  noReportDays: new Set(), history: [],
  batchMembersCache: {},
  // ui state
  tab: 'checkin', rolesTab: 'AM',
  locStatus: 'idle', locDistance: null, locGpsMsg: '',
  accountOpen: false, confirmDelete: false,
  viewOffset: 0, avatars: {}, selectedCalOffset: null,
  npName: '', npContact: '', npShift: 'AM', npPassword: '',
  rosterSearch: '',
  realtimeChannel: null,
  now: new Date(), demo: false,
  isOnline: typeof navigator !== 'undefined' ? navigator.onLine : true,
  offlinePending: false,
  phaseSubmitting: false,
  acctNameEdit: '',
  acctPwCurrent: '', acctPwNew: '', acctPwConfirm: '',
  acctPwError: '', acctPwSuccess: '', capsLock: false,
  acctNameError: '', acctNameSuccess: '',
  acctSaving: false,
  locPhase: null, locSlow: false, locAccuracy: null, locPermErr: false, locRetryCount: 0,
  isInAppBrowser: false, inAppBrowserName: '',
  batchLoading: false, batchCreating: false, markingAllAbsent: false, confirmMarkAllAbsent: false, logShiftFilter: 'all',
  editingNoteId: null, editingNoteText: '',
  batchJumpDate: Utils.dateKey(new Date()),
  toast: null,
  rosterSort: 'shift',
  newBatchDate: '',
  noAvatarIds: new Set(),
  peopleStats: {}, peopleStatsLoaded: false,
  confirmDeactivateId: null,
  showArchivedBatches: false,
  cyclePickerOpen: false, cyclePickerYear: null, cyclePickerPage: 1,
  attendanceDate: null,
  noReportDaysCache: {},
  markAllPresenting: false,
  editingBatchLabel: false, batchLabelText: '',
  historyPage: 1,
  sessionExpiring: false,
  idleWarning: false,
  timesEditId: null, timesEditP1: '', timesEditP2: '', timesEditP3: '', timesEditP4: '', timesEditSaving: false, timesEditErrField: null,
  showA2hs: false, a2hsIsIos: false,
  forgotPasswordOpen: false,
  showLateWarning: false,
  lateReasonOpen: false, lateReasonText: '', lateReasonSubmitting: false,
  leaveOpen: false, leaveDate: '', leaveType: 'mc', leaveReason: '',
  myPendingRequest: null,
  pendingLeaves: [], pendingLeavesLoaded: false,
  shiftChangeOpen: false, shiftChangeNew: 'AM', shiftChangeReason: '', shiftChangeConfirming: false,
  adminNotifGranted: false,
  myLeaveHistory: [], myLeaveHistoryLoaded: false,
  welfareNoteOpen: false, welfareNoteText: '', welfareNoteSaving: false,
  isSuperAdmin: false,
  adminsList: [], adminsLoaded: false,
  npAdminName: '', npAdminContact: '', npAdminPassword: '',
  confirmDeactivateAdminId: null,
  promoteAdminId: '', promoteAdminName: '', promoteAdminContact: '', confirmPromoteAdminId: null, promoteSearch: '', promoteShowAllCycles: false, promoteListPage: 1,
  peopleTab: 'requests', addPersonnelOpen: false, npReenrollRecord: null,
  signupPending: false,
  pendingSignups: [], pendingSignupsLoaded: false,
  approvedSignups: [],
  selectedSignupIds: [],
  signupSearch: '', leaveSearch: '',
  rejectLeaveId: null, rejectLeaveReason: '',
  waPreviewOpen: false, waPreviewText: '',
  logNoteId: null, logNoteText: '',
  logSearch: '',
  personHistoryId: null, personHistoryRows: [], personHistoryLoading: false,
  realtimeLive: false,
  resetPwId: null, resetPwNew: '', resetPwSaving: false,
  broadcastOpen: false, broadcastText: '', broadcastSaving: false,
  bulkAddOpen: false, bulkAddText: '', bulkAddParsed: [], bulkAddStep: 'input', bulkAddAdding: false,
  noReportBulkOpen: false, noReportBulkText: '',
  helpOpen: false,
});
